spring:
  application:
    name: pop4u

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pop4u?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: newuser
    password: newpassword

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 기존 데이터 유지하며 테이블 자동 업데이트
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always  # 서버 실행 시 초기 데이터(`data.sql`) 삽입
